version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
        - .:/app
        - /app/node_modules
    networks:
      - app-network
    command: ["yarn", "start:dev"]

volumes:
  redis-data:

networks:
    app-network: