services:
  redis:
    image: redis:7.2
    container_name: redis
    environment:
     - REDIS_PORT=6379
     - REDIS_HOST=redis
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redis-data:/data
    restart: no

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - redis
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
        - .:/app
        - /app/node_modules
    networks:
      - app-network
    command: ["yarn", "start:dev"]

volumes:
  redis-data:

networks:
    app-network: